#include "alias.inc"
module blacs_basics
    implicit none
    logical :: flag_use_blacs
    integer :: mpi_comm_blacs
    integer :: myid_blacs
    integer, allocatable :: id_blacs(:)
    integer*4         :: nprow ! copied from COMM_EARTH
    integer*4         :: npcol ! copied from COMM_EARTH
    ! myrow, mycol is generated by proc_map routine
    integer*4         :: myrow
    integer*4         :: mycol

    integer, parameter :: BLOCK_CYCLIC_2D = 1
    integer, parameter :: DTYPE_=1, &
                           CTXT_=2, &
                              M_=3, &
                              N_=4, &
                             MB_=5, &
                             NB_=6, &
                           RSRC_=7, &
                          CSRC_ =8, &
                            LLD_=9, &
                           DLEN_=9


endmodule blacs_basics
