#!/local/th1/iff003/kim/anaconda3/bin/python
import sys
from mpi4py import MPI
import tbfitpy as tbfit
import time

# initialize MPI
comm = MPI.COMM_WORLD ; nprocs = comm.Get_size() ; myid = comm.Get_rank() 

# set mytb 
mytb = tbfit.pytbfit(mpicomm=comm)

# In this example we will try two different optimization scheme
# 1. PSO method with LMDIF method
n_particles = 50
method='mypso.lmdif' 
mytb.init( myid = myid)
pso_options={'c1': 0.3, 'c2': 0.4, 'w':0.2}
mytb.fit(verbose=True, method=method, miter = 30, n_particles=n_particles, pso_options=pso_options, iseed = 123)
mytb.save(title=method , plot_fit=True, target=False, band=False, param=True , weight=False, cost_history=True)

# 2. LMDIF method alone
method='lmdif'
mytb.init( myid = myid )
mytb.fit(verbose=True , method=method, miter=100)
mytb.save(title=method , plot_fit=True, target=False, band=False, param=True , weight=False, cost_history=True)
